### PR TITLE
fix: package export files

### LINKED ISSUE #987: ESLint warning: Package subpath './dist/react-tooltip' is not defined
**Describe the bug**
When importing:
```
import 'react-tooltip/dist/react-tooltip.css';
```

I see the following error through eslint:
```
Resolve error: Package subpath './dist/react-tooltip' is not defined by "exports" in /Users/[username]/Sites/[projectname]/node_modules/react-tooltip/package.json
```

I'm not sure exactly where './dist/react-tooltip' is being requested (not in my codebase), but adding this to the react-tooltip package `exports` resolves it:
```
"exports": {
    ...
    "./dist/react-tooltip": "./dist/react-tooltip.cjs.js"
  },
```

**Version of Package**
v5.10.1-beta.4

### LINKED ISSUE #1000: [BUG] Missing "main" and "module" entries in "package.json"
**Describe the bug**
Missing "main" and "module" entries in "package.json" causes nodejs (npm/yarnpkg) to not find the correct entries

**Version of Package**
v5.10.5

Regression from #984 . See https://github.com/ReactTooltip/react-tooltip/pull/984/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L21 .

"main" and "module" are still required for compatibility with other tools, such as nodejs. See https://rollupjs.org/introduction/#publishing-es-modules .

**Additional context**
I believe you want
```json
  "main": "dist/react-tooltip.min.cjs",
  "module": "dist/react-tooltip.min.mjs",
```
(the original entries were
```json
  "main": "dist/react-tooltip.cjs.min.js",
  "module": "dist/react-tooltip.esm.min.js",
```
)

### LINKED ISSUE #1002: What is the appropriate way to import & setup react-tooltip as of 5.10.5?
Hi react-tooltip devs!

I was attempting to upgrade from 5.10.0 to 5.10.5, and noticed what seem to be some changes in the build. I wasn't sure if these changes were expected (the `README` doesn't seem to have changed), so wanted to ask you directly.

Here's what I see on my local machine after using npm to install version 5.10.5:

```
➜  ls -l node_modules/react-tooltip/dist/
-rw-r--r--    201 Apr  5 11:38 react-tooltip-tokens.css
-rw-r--r--  36970 Apr  5 11:38 react-tooltip.cjs
-rw-r--r--  64070 Apr  5 11:38 react-tooltip.cjs.map
-rw-r--r--   4334 Apr  5 11:38 react-tooltip.d.ts
-rw-r--r--  12355 Apr  5 11:38 react-tooltip.min.cjs
-rw-r--r--  51359 Apr  5 11:38 react-tooltip.min.cjs.map
-rw-r--r--   1295 Apr  5 11:38 react-tooltip.min.css
-rw-r--r--  11787 Apr  5 11:38 react-tooltip.min.mjs
-rw-r--r--  51067 Apr  5 11:38 react-tooltip.min.mjs.map
-rw-r--r--  36173 Apr  5 11:38 react-tooltip.mjs
-rw-r--r--  63803 Apr  5 11:38 react-tooltip.mjs.map
-rw-r--r--  40803 Apr  5 11:38 react-tooltip.umd.js
-rw-r--r--  64168 Apr  5 11:38 react-tooltip.umd.js.map
-rw-r--r--  12596 Apr  5 11:38 react-tooltip.umd.min.js
-rw-r--r--  51379 Apr  5 11:38 react-tooltip.umd.min.js.map
```

First, there is no longer a non-minified CSS file, i.e., there is no longer a `react-tooltip.css`. Was that intentional? I'm noticing that the README still refers to the non-minified file; the README also states that are minified and non-minified versions of each module.

Second, trying to import directly as `react-tooltip` doesn't seem to work anymore - i think possibly because instead of having `esm` and `cjs` modes, there's now just a `*.cjs` or `*.mjs`. What's the correct way to import those files? By specifying, e.g., `import XXX from @react-tooltip.mjs`?

Thanks again!
tliu30

### LINKED ISSUE #1004: [Question] Cannot find module `react-tooltip/dist/react-tooltip.css`
**Describe the bug**
When running tests via Jest. Get error `Cannot find module 'react-tooltip/dist/react-tooltip.css'`
As i can see, file was removed in this version.
**Version of Package**
v5.10.5

**Screenshots**
image

### PR DESCRIPTION
**Pull request by danielbarion**
* update rollup-build to output missed normal CSS file

close #1004 
close #1002 
close #1000 
close #987

### CODE REVIEW

**Comment by danielbarion** [comment]
Beta version:
```
yarn add react-tooltip@5.10.6-beta.1005.1
```
or
```
npm i react-tooltip@5.10.6-beta.1005.1
```

**Comment by danielbarion** [comment]
Beta version:
```
yarn add react-tooltip@5.10.6-beta.1005.2
```
or
```
npm i react-tooltip@5.10.6-beta.1005.2
```

**Comment by gabrieljablonski** [comment]
Something to consider, is it viable to automatically import the CSS file? Sso when using the component you no longer need to

```jsx
import 'react-tooltip/dist/react-tooltip.css'
```

**Comment by GorvGoyl** [comment]
> Something to consider, is it viable to internally import the CSS file? So when using the component you no longer need to
> 
> ```js
> import 'react-tooltip/dist/react-tooltip.css'
> ```

I just started tinkering with react-tooltip and I'd also prefer react-tooltip to preload any css styles. importing css file especially in shadow dom on top of custom loader is PITA.

**Pull request merged**
