### PR TITLE
chore: dependencies upgrade

### PR DESCRIPTION
**Pull request by danielbarion**
Upgrading dependencies and some informations of the project (like maintainers and the new repo structure inside ReactTooltip)

### CODE REVIEW

**Comment by aronhelser** [comment]
Another thing to think about is the demo webpage - it was on [github-pages](https://wwayne.github.io/react-tooltip) but looks like it's nuked somehow.

**Comment by danielbarion** [comment]
Oh, I'll check as soon as possible @aronhelser, thanks for realizing that!

That PR is still in draft, I'm updating the major dependencies and testing after each package gets upgraded, so, that PR will take a few more hours/days to get ready to go.

**Comment by danielbarion** [comment]
One question: I never did a GitHub page from an organization, just from personal GitHub account, so, maybe we need to consider using some tool like `Netlify` to show the demo page as static assets, right?

hey, @pdeszynski I've added you to the readme as a maintainer, please feel free to update your current status.

**Comment by danielbarion** [comment]
@aronhelser, as that PR contains a fix https://github.com/ReactTooltip/react-tooltip/pull/799/commits/aae936e2f7a820cf1edcb68927b8973051dae9c2 and docs update, like the demo page, I'll stop the dependency upgrades here and I'll do another PR for the others that need to be upgraded, please, feel free to review and merge that PR when you can.

Thanks!

**Comment by aronhelser** [comment]
I'll leave it to you to merge when you are ready.
LGTM, +1

**Pull request merged**
